sudo: false
language: rust

# Prevents cargo's cache from growing to large, see https://levans.fr/rust_travis_cache.html
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
    - "$TRAVIS_BUILD_DIR/redis_tmp" # build redis from source

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

before_install: |
  sudo add-apt-repository ppa:chris-lea/redis-server -y
  sudo apt-get update
  sudo apt-get install redis-server -y

matrix:
  include:
    - rust: stable
      env: RUST_VERSION=stable COMMAND=test-ci REDIS_BRANCH=6.0.5

    - rust: beta
      env: RUST_VERSION=beta COMMAND=test-ci REDIS_BRANCH=6.0.5

    - rust: nightly
      env: RUST_VERSION=nightly COMMAND=test-ci REDIS_BRANCH=6.0.5

    - rust: stable
      env: COMMAND=lint

script:
  - redis-server --version

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
